version: '3.8'

services:
  write-db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: advanced_postgres_db
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  read-db:
    image: mongo
    restart: always
    container_name: advanced_mongo_db
    volumes:
      - ./mongo-db:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGODB_DATABASE="vf-read-db"

  event-store:
    image: mongo:8.0
    restart: always
    ports:
      - 27018:27017
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    container_name: advanced_event_store
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
