services:
  postgres-db:
    container_name: postgres-db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgAdmin:
    depends_on:
      - postgres-db
    image: dpage/pgadmin4:9.12.0
    container_name: pgAdmin
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASSWORD}
      - PGADMIN_DEFAULT_USERNAME=${PG_ADMIN_USERNAME}
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
    restart: always