services:

  # NATS Server
  nats-server:
    image: nats:latest

# =================================================
# Client Gateway Connections
# =================================================

  # Client Gateway
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    image: client-gateway-prod
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
    restart: always

# =================================================
# Microservices
# =================================================

  # Products MicroService
  products-app:
    build: 
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: products-ms-prod
    ports:
      - ${PRODUCTS_APP_PORT}:${PRODUCTS_APP_PORT}
    environment:
      - PORT=${PRODUCTS_APP_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=file:./dev.db
    restart: always

  # Order MicroService
  # orders-app:
  #   container_name: orders_ms
  #   build: ./orders-ms
  #   ports:
  #     - ${ORDERS_APP_PORT}:3002
  #   volumes:
  #     - ./orders-ms/src:/usr/src/app/src
  #   command: npm run start:dev
  #   environment:
  #     - PORT=${ORDERS_APP_PORT}
  #     - NATS_SERVERS=${NATS_SERVERS}
  #     - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@orders-db:5432/${DB_NAME}?schema=public
  #   restart: always
  #   depends_on:
  #     orders-db:
  #       condition: service_healthy
  #       restart: true

  # Payments MicroService
  payments-app:
    build: 
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: payments-ms-prod
    ports:
      - ${PAYMENTS_APP_PORT}:${PAYMENTS_APP_PORT}
    environment:
      - PORT=${PAYMENTS_APP_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
    restart: always

  # Auth Microservice
  auth-app:
    build: 
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: auth-ms-prod
    ports:
      - ${AUTH_APP_PORT}:${AUTH_APP_PORT}
    environment:
      - PORT=${AUTH_APP_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${DATABASE_MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always